# Generated by Django 5.2.3 on 2025-06-16 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizebycolorproductrelations',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.size'),
        ),
    ]
