# Generated by Django 5.2.3 on 2025-06-17 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_alter_sizebycolorproductrelations_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='color_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.colorproductrelations'),
        ),
    ]
